# Generated by Django 4.1 on 2023-03-23 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=124)),
                ("dob", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("Female", "Female")], max_length=10
                    ),
                ),
                ("email", models.EmailField(max_length=100)),
                ("phone", models.IntegerField()),
                ("address", models.CharField(max_length=100)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("Enquiry", "Enquiry"),
                            ("Place Order", "Place Order"),
                            ("Return", "Return"),
                            ("Others", "Others"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.RenameModel(old_name="course", new_name="City",),
        migrations.RenameModel(old_name="department", new_name="Country",),
        migrations.DeleteModel(name="store",),
        migrations.AddField(
            model_name="person",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="store.city",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="store.country",
            ),
        ),
    ]
